//
//  MockData.swift
//  Real_State
//
//  Datos locales para el prototipo offline.
//

import Foundation
import CoreLocation
import MapKit

enum MockData {

    static let agents: [Agent] = [
        Agent(id: UUID(uuidString: "a1b2c3d4-0001-4000-8000-000000000001")!,
              name: "Sarah Mitchell",
              rating: 4.9,
              reviewCount: 127,
              company: "Premier Realty",
              phone: "+1 (555) 123-4567",
              email: "sarah.mitchell@premierrealty.com"),
        Agent(id: UUID(uuidString: "a1b2c3d4-0002-4000-8000-000000000002")!,
              name: "James Chen",
              rating: 4.8,
              reviewCount: 89,
              company: "Urban Homes",
              phone: "+1 (555) 234-5678",
              email: "james.chen@urbanhomes.com"),
        Agent(id: UUID(uuidString: "a1b2c3d4-0003-4000-8000-000000000003")!,
              name: "Emily Rodriguez",
              rating: 5.0,
              reviewCount: 64,
              company: "Luxury Estates",
              phone: "+1 (555) 345-6789",
              email: "emily.r@luxuryestates.com")
    ]

    /// Centro del mapa: Houston, TX
    static let houstonCenter = CLLocationCoordinate2D(latitude: 29.7604, longitude: -95.3698)

    static let properties: [Property] = [
        // --- 5 RESIDENCIALES ---
        Property(
            id: UUID(uuidString: "b2c3d4e5-0001-4000-8000-000000000001")!,
            title: "Modern Home with Garden",
            address: "1245 Main St",
            city: "Houston",
            state: "TX",
            price: 485_000,
            bedrooms: 4,
            bathrooms: 3,
            squareFeet: 2400,
            listingType: .sale,
            category: .residential,
            propertyType: .house,
            description: "Beautiful two-story home with contemporary design. Well-maintained lawn, renovated kitchen, and nearby schools.",
            amenities: ["Garage", "AC", "Garden", "Porch"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7604, longitude: -95.3698),
            agentId: agents[0].id,
            isNewListing: true,
            isOpenHouse: true,
            imageStyleIndex: 0,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0002-4000-8000-000000000002")!,
            title: "Family Home in The Heights",
            address: "789 Oak Avenue",
            city: "Houston",
            state: "TX",
            price: 525_000,
            bedrooms: 4,
            bathrooms: 3.5,
            squareFeet: 2800,
            listingType: .sale,
            category: .residential,
            propertyType: .house,
            description: "Spacious family home on a quiet street. Updated kitchen, large backyard, and excellent schools nearby.",
            amenities: ["Garden", "Garage", "AC", "Fireplace"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7950, longitude: -95.4690),
            agentId: agents[1].id,
            isNewListing: false,
            isOpenHouse: false,
            imageStyleIndex: 1,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0003-4000-8000-000000000003")!,
            title: "House for Rent - Midtown",
            address: "456 Harbor Dr",
            city: "Houston",
            state: "TX",
            price: 2_400,
            bedrooms: 3,
            bathrooms: 2,
            squareFeet: 1850,
            listingType: .lease,
            category: .residential,
            propertyType: .house,
            description: "Spacious house near restaurants and transit. Pet-friendly.",
            amenities: ["Patio", "Garage", "AC"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7354, longitude: -95.4100),
            agentId: agents[2].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 2,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0004-4000-8000-000000000004")!,
            title: "Stylish Townhouse",
            address: "321 Elm Street",
            city: "Houston",
            state: "TX",
            price: 398_000,
            bedrooms: 3,
            bathrooms: 2,
            squareFeet: 1650,
            listingType: .sale,
            category: .residential,
            propertyType: .townhouse,
            description: "Charming townhouse steps from cafes and parks. Recently renovated.",
            amenities: ["Patio", "Garage", "AC"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7180, longitude: -95.4200),
            agentId: agents[0].id,
            isNewListing: false,
            isOpenHouse: true,
            imageStyleIndex: 3,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0005-4000-8000-000000000005")!,
            title: "New Home in Sugar Land",
            address: "555 Midtown Blvd",
            city: "Sugar Land",
            state: "TX",
            price: 675_000,
            bedrooms: 5,
            bathrooms: 4,
            squareFeet: 3200,
            listingType: .sale,
            category: .residential,
            propertyType: .house,
            description: "New construction with luxury finishes. Exclusive neighborhood with amenities.",
            amenities: ["Pool", "2-Car Garage", "AC", "Garden"],
            coordinate: CLLocationCoordinate2D(latitude: 29.6200, longitude: -95.6350),
            agentId: agents[1].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 4,
            imageName: "PropertyHouse"
        ),
        // --- 5 COMERCIALES ---
        Property(
            id: UUID(uuidString: "b2c3d4e5-0006-4000-8000-000000000006")!,
            title: "Galleria Office Space",
            address: "5000 Westheimer Rd",
            city: "Houston",
            state: "TX",
            price: 2_850_000,
            bedrooms: 0,
            bathrooms: 4,
            squareFeet: 3800,
            listingType: .sale,
            category: .commercial,
            propertyType: .office,
            description: "Office space with 360° city views. Private elevator, conference rooms, and rooftop terrace.",
            amenities: ["Rooftop", "Elevator", "Parking", "Doorman"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7374, longitude: -95.4624),
            agentId: agents[2].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 0,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0007-4000-8000-000000000007")!,
            title: "Corner Retail Unit",
            address: "2100 Post Oak Blvd",
            city: "Houston",
            state: "TX",
            price: 1_450_000,
            bedrooms: 0,
            bathrooms: 2,
            squareFeet: 2200,
            listingType: .lease,
            category: .commercial,
            propertyType: .retail,
            description: "High-traffic corner retail space. Great visibility and parking.",
            amenities: ["Parking", "Storefront", "AC"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7284, longitude: -95.4614),
            agentId: agents[0].id,
            isNewListing: false,
            isOpenHouse: false,
            imageStyleIndex: 1,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0008-4000-8000-000000000008")!,
            title: "Industrial Warehouse",
            address: "8500 Kirby Dr",
            city: "Houston",
            state: "TX",
            price: 1_200_000,
            bedrooms: 0,
            bathrooms: 2,
            squareFeet: 12000,
            listingType: .sale,
            category: .commercial,
            propertyType: .office,
            description: "Industrial warehouse with loading dock. High ceilings, loading door.",
            amenities: ["Loading", "Parking", "AC"],
            coordinate: CLLocationCoordinate2D(latitude: 29.6780, longitude: -95.4850),
            agentId: agents[1].id,
            isNewListing: false,
            isOpenHouse: false,
            imageStyleIndex: 2,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0009-4000-8000-000000000009")!,
            title: "Downtown Office",
            address: "1000 Main St",
            city: "Houston",
            state: "TX",
            price: 3_100_000,
            bedrooms: 0,
            bathrooms: 6,
            squareFeet: 5500,
            listingType: .sale,
            category: .commercial,
            propertyType: .office,
            description: "Full floor in corporate tower. Downtown views, premium finishes.",
            amenities: ["Lobby", "Elevator", "Parking", "24h Security"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7540, longitude: -95.3620),
            agentId: agents[2].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 3,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0010-4000-8000-000000000010")!,
            title: "Mixed-Use Space Houston",
            address: "3200 Montrose Blvd",
            city: "Houston",
            state: "TX",
            price: 890_000,
            bedrooms: 0,
            bathrooms: 3,
            squareFeet: 2800,
            listingType: .lease,
            category: .commercial,
            propertyType: .retail,
            description: "Retail space with office on upper floor. Ideal for restaurant or shop.",
            amenities: ["Kitchen", "Parking", "AC"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7280, longitude: -95.4020),
            agentId: agents[0].id,
            isNewListing: false,
            isOpenHouse: false,
            imageStyleIndex: 4,
            imageName: "PropertyHouse"
        ),
        // --- 5 TERRENOS ---
        Property(
            id: UUID(uuidString: "b2c3d4e5-0011-4000-8000-000000000011")!,
            title: "Cypress Land - 2.5 acres",
            address: "18000 FM 529",
            city: "Houston",
            state: "TX",
            price: 890_000,
            bedrooms: 0,
            bathrooms: 0,
            squareFeet: 0,
            listingType: .sale,
            category: .land,
            propertyType: .lot,
            description: "Lot ready for development. Utilities available. Mixed-use zoning.",
            amenities: ["Utilities", "Highway Access"],
            coordinate: CLLocationCoordinate2D(latitude: 29.9684, longitude: -95.6898),
            agentId: agents[1].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 0,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0012-4000-8000-000000000012")!,
            title: "Katy Lot - 1.2 acres",
            address: "24500 Katy Fwy",
            city: "Katy",
            state: "TX",
            price: 425_000,
            bedrooms: 0,
            bathrooms: 0,
            squareFeet: 0,
            listingType: .sale,
            category: .land,
            propertyType: .lot,
            description: "Flat lot with direct access. Ideal for single-family home.",
            amenities: ["Utilities", "Paved Street"],
            coordinate: CLLocationCoordinate2D(latitude: 29.7850, longitude: -95.7520),
            agentId: agents[2].id,
            isNewListing: false,
            isOpenHouse: false,
            imageStyleIndex: 1,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0013-4000-8000-000000000013")!,
            title: "Tomball Parcel - 5 acres",
            address: "15200 FM 2920",
            city: "Tomball",
            state: "TX",
            price: 650_000,
            bedrooms: 0,
            bathrooms: 0,
            squareFeet: 0,
            listingType: .sale,
            category: .land,
            propertyType: .lot,
            description: "Rural land with trees. Subdivision possible. Owner financing available.",
            amenities: ["Water", "Electricity"],
            coordinate: CLLocationCoordinate2D(latitude: 30.0950, longitude: -95.6200),
            agentId: agents[0].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 2,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0014-4000-8000-000000000014")!,
            title: "Spring Land - 0.8 acres",
            address: "22600 Kuykendahl Rd",
            city: "Spring",
            state: "TX",
            price: 285_000,
            bedrooms: 0,
            bathrooms: 0,
            squareFeet: 0,
            listingType: .sale,
            category: .land,
            propertyType: .lot,
            description: "Lot in growing area. Near The Woodlands and I-45.",
            amenities: ["Utilities", "Easy Access"],
            coordinate: CLLocationCoordinate2D(latitude: 30.0580, longitude: -95.4180),
            agentId: agents[1].id,
            isNewListing: false,
            isOpenHouse: false,
            imageStyleIndex: 3,
            imageName: "PropertyHouse"
        ),
        Property(
            id: UUID(uuidString: "b2c3d4e5-0015-4000-8000-000000000015")!,
            title: "Pearland Ranch - 10 acres",
            address: "9800 Broadway St",
            city: "Pearland",
            state: "TX",
            price: 1_250_000,
            bedrooms: 0,
            bathrooms: 0,
            squareFeet: 0,
            listingType: .sale,
            category: .land,
            propertyType: .lot,
            description: "Expansive property with lake. Ideal for development or agricultural use.",
            amenities: ["Lake", "Fenced", "Utilities"],
            coordinate: CLLocationCoordinate2D(latitude: 29.5550, longitude: -95.3520),
            agentId: agents[2].id,
            isNewListing: true,
            isOpenHouse: false,
            imageStyleIndex: 4,
            imageName: "PropertyHouse"
        )
    ]

    static let userProfile = UserProfile(
        name: "Alex Johnson",
        avatarEmoji: "👤",
        recentlySearchedLocations: ["Houston, TX", "The Woodlands, TX", "Katy, TX", "Sugar Land, TX"]
    )

    static let settingsItems: [SettingsItem] = [
        SettingsItem(title: "Notifications", systemImage: "bell.fill"),
        SettingsItem(title: "Privacy", systemImage: "lock.fill"),
        SettingsItem(title: "Payment Methods", systemImage: "creditcard.fill"),
        SettingsItem(title: "Help & Support", systemImage: "questionmark.circle.fill"),
        SettingsItem(title: "About", systemImage: "info.circle.fill")
    ]

    /// Gradientes para imágenes fake por índice
    static let heroGradientColors: [[String]] = [
        ["#1a1a2e", "#16213e"],
        ["#2d132c", "#801336"],
        ["#0f3460", "#16213e"],
        ["#1b262c", "#0f3460"],
        ["#2c3e50", "#3498db"],
        ["#e74c3c", "#c0392b"]
    ]
}
